[package]
name = "guest_code_for_zk_proof"
version = "0.1.0"
edition = "2021"

[workspace]


[dependencies]
risc0-zkvm = { version = "3.0.3", default-features = false, features = ['std'] }
ream-consensus-lean = { path = "../../../../../common/consensus/lean" }

[patch.crates-io]
ethereum_hashing = { git = "https://github.com/ReamLabs/ethereum_hashing.git" }