[package]
name = "guest_code_for_zk_proof"
version = "0.1.0"
edition = "2021"

[workspace]


[dependencies]
ream-consensus-lean = { path = "../../../../../common/consensus/lean" }
ere-platform-sp1 = { git = "https://github.com/eth-act/ere.git" }

[patch.crates-io]
ethereum_hashing = { git = "https://github.com/ReamLabs/ethereum_hashing.git" }