[package]
name = "ream-prover-lean"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
# External dependencies
alloy-primitives.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tree_hash.workspace = true

# Ream dependencies
ream-chain-lean.workspace = true
ream-consensus-lean.workspace = true
ream-network-spec.workspace = true
ream-storage.workspace = true

# risc0 dependencies
methods = { path = "./methods" }
risc0-zkvm = { version = "3.0.3" }

[lints]
workspace = true
